### ISSUE TITLE
MIDIEvent [and MIDIConnectionEvent] lacking constructor

### ISSUE THREAD

**Issue by jussi-kalliokoski** [WebAudio/web-midi-api#1]
> Originally reported on W3C Bugzilla [ISSUE-20512](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512) Mon, 24 Dec 2012 10:45:24 GMT
> Reported by Marcos Caceres
> Assigned to This bug has no owner yet - up for the taking

The MIDIEvent is lacking a way for authors to construct MIDI events. 

[Constructor(DOMString type, optional MIDIEventInit eventInitDict)]
interface MIDIEvent : Event {
    readonly attribute DOMHighResTimeStamp timestamp;
    readonly attribute Uint8Array          data;
};

dictionary MIDIEventInit : EventInit {
  any data;
};

(note that I left data as any, assuming UInt8Array conversion will be performed automatically).

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#0) by Chris Wilson on W3C Bugzilla. Wed, 26 Dec 2012 17:10:53 GMT

Why should you ever need to construct a MIDIEvent?

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#1) by Marcos Caceres on W3C Bugzilla. Wed, 26 Dec 2012 17:17:47 GMT

(In reply to [comment #1](#issuecomment-12111983))

> Why should you ever need to construct a MIDIEvent?

This one is for consistency with the rest of the Web platform (every event in the platform has a public constructor, AFAIK).  

Use case is primarily for testing through constructing and firing synthetic events....

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#2) by Chris Lilley on W3C Bugzilla. Tue, 08 Jan 2013 16:45:45 GMT

(In reply to [comment #1](#issuecomment-12111983))

> Why should you ever need to construct a MIDIEvent?

Because you are writing a sequencer, auto-chord maker, arpeggiator, etc?

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#3) by Chris Wilson on W3C Bugzilla. Tue, 08 Jan 2013 17:46:04 GMT

(In reply to [comment #3](#issuecomment-12111992))

> (In reply to [comment #1](#issuecomment-12111983))
> 
> > Why should you ever need to construct a MIDIEvent?
> 
> Because you are writing a sequencer, auto-chord maker, arpeggiator, etc?

That's a great reason why you should need to maintain MIDI event data - but not really a justification for why you would want to create an Event-derived object that contains said data.  This isn't just a data container - it has all the Event stuff, too - and it's no longer used for sending data.  (For an arpeggiator, for example, you'd just create the data array for each note and call send().)

Marcos' "primarily for testing, firing synthetic events" is a justifiable reason, I suppose; however, I'm not sure I see how this is done in other specs.  Is there a TouchEvent constructor somewhere?

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#4) by Marcos Caceres on W3C Bugzilla. Tue, 08 Jan 2013 19:19:28 GMT

(In reply to [comment #4](#issuecomment-12111998)) 

> Marcos' "primarily for testing, firing synthetic events" is a justifiable
> reason, I suppose; however, I'm not sure I see how this is done in other
> specs.  Is there a TouchEvent constructor somewhere?

The TouchEvent spec is not a good guide as it lacks a link to UIEvent (maybe that spec has not been well reviewed, but not sure). 

I recommend looking at the new DOM UI Events spec... there is a whole section on constructors for events (the spec is currently not loading well in Chrome, so use FF or something else to view it):

https://dvcs.w3.org/hg/d4e/raw-file/tip/source_respec.htm

As an aside, the Event interface, from which MIDIEvent inherits, has a constructor. But I'm having trouble finding in WebIDL what it means to inherit from an interface that has a constructor on it.

**Comment by jussi-kalliokoski** [comment]
> [Original comment](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20512#5) by Chris Wilson on W3C Bugzilla. Tue, 08 Jan 2013 19:26:57 GMT

(In reply to [comment #5](#issuecomment-12112007))

> (In reply to [comment #4](#issuecomment-12111998)) 
> 
> > Marcos' "primarily for testing, firing synthetic events" is a justifiable
> > reason, I suppose; however, I'm not sure I see how this is done in other
> > specs.  Is there a TouchEvent constructor somewhere?
> 
> The TouchEvent spec is not a good guide as it lacks a link to UIEvent (maybe
> that spec has not been well reviewed, but not sure). 
> 
> I recommend looking at the new DOM UI Events spec... there is a whole
> section on constructors for events (the spec is currently not loading well
> in Chrome, so use FF or something else to view it):
> 
> https://dvcs.w3.org/hg/d4e/raw-file/tip/source_respec.htm
> 
> As an aside, the Event interface, from which MIDIEvent inherits, has a
> constructor. But I'm having trouble finding in WebIDL what it means to
> inherit from an interface that has a constructor on it.

I would think this would be symmetric with UI Events - so the answer to "how do I synthesize a MIDIEvent" would be:

var event = new Event("message", {data: [...], timestamp: t });

**Comment by notator** [comment]
It would be nice to have a MIDIEvent constructor when using a Standard MIDI File as input to an application, but maybe that code is best put in a javascript library... for the moment, at least...

**Comment by notator** [comment]
Replaced my original post here. It was no longer useful.

I've been re-working my Jazz-Plugin based project [1] over the past few weeks, and will be uploading a major revision in the next few days [2].
Here's what I now think. As far as I'm concerned, this issue could be rounded off.

I've put my re-usable MIDI code (intermediary between the Jazz API and my application code) into a re-usable library. That's where there's a blurry line between what might go in the Web MIDI API and what might go in a Javascript library.

From a Javascript programmer's point of view, I no longer think it matters much if there's a constructor for a MIDIEvent or not. All we need is a standard way to receive input events.

Output:
At least in my application, its much better to work with timestamped collections of messages. Not every message needs its own timestamp.
Its like Chris said:

> For an arpeggiator, for example, you'd just create the data array for each note and call send().

The collections I'm using also have application-specific attributes, so there's no point in trying to standardize them (at least for the moment) in the Web MIDI API. They currently belong in a Javascript library.

Input
Timestamped collections of messages could also be used conveniently when reading Standard MIDI Files, but there again I think such constructors belong in a Javascript library -- at least for now.

Possible further issues:
I'd  prefer what is being called a MIDIEvent to be called a MIDIInputEvent. That would make it clearer what we are talking about. MIDIOutputEvents are something else entirely, and should be allowed for.

Messages: I currently have a fairly complex Message pseudo-class (consisting of various sizes of UInt8Array). Something like that might also be a candidate for the Web MIDI API, but I don't need it to be there, so it would be best to leave it out.

best,
James

[1] https://github.com/notator/assistant-performer
[2] I'll announce it on
http://lists.w3.org/Archives/Public/public-audio-dev/

**Comment by cwilso** [comment]
Bump: do we need a constructor, or does 
var event = new Event("message", {data: [...], timestamp: t });

suffice?  I'm guessing the answer is we still need a constructor.

**Comment by marcoscaceres** [comment]
I think you should add an explicit constructor given that you are adding an implicit one.

**Comment by marcoscaceres** [comment]
We will also need to specify how to construct it both implicitly and explicitly.

**Comment by cwilso** [comment]
Fixed.
