### ISSUE TITLE
MidiMessageEvent.receivedTime and AudioContext.currentTime

### ISSUE THREAD

**Issue by bjornm** [WebAudio/web-midi-api#101]
Hi, I'm having trouble syncing incoming midi messages with the web audio context. Not sure what the web audio spec says, but from looking at blink's AudioDestinationNode.cpp, currentTime advances in discrete steps of 128 / sampleRate every render quantum. This makes syncing against performance.now() off by between 0 and 3ms @44100 Hz, depending on when you ask. 

One solution would be for AudioContext (or Web Midi) to provide translation between the two timelines:

var audioTime = audioContext.performanceToContextTime(event.receivedTime);

Comments, thoughts? I might be missing something here - if so, please enlighten me :)

Cheers,
Bjorn

**Comment by cwilso** [comment]
Yep, need to be able to do this in Web Audio.  (Web MIDI just runs in system-clock time.)  Tracked over here: https://github.com/WebAudio/web-audio-api/issues/12.
