### ISSUE TITLE
Request for explicit MIDI port state management

### ISSUE THREAD

**Issue by bome** [WebAudio/web-midi-api#104]
This is a follow up to issue #75 (and to #2).

As I understand it, ports are opened implicitly when you set the `onmidimessage` handler, or `send()` a message. This will usually require the implementation to allocate some system resources. The current WebMIDI API does not give a way to deallocate such resources (for MIDIInput, you could establish the convention that setting `onmidimessage` to null will close the port, but there is no equivalent for MIDIOutput).

Furthermore, exclusive ports are not a "problem" of Windows (or some drivers), but are a typical model for accessing hardware resources. ALSA's rawmidi on Linux will allow you to use exclusive ports, too (for best performance). I see shared MIDI ports as a convenience (not without risks, e.g. when merging) that a general purpose API should not rely on.

Now if we want the WebMIDI API to give meaningful and predictable results with exclusive MIDI ports, I suggest adding something to the effect of the following:

1) a state enum:

```
enum MIDIState {
    disconnected,
    closed, // = connected
    open
};
```

2) these methods to the MIDIPort interface:

```
void open();
void close();
MIDIState getState();
```

MIDIOutput.send() should be extended to throw an exception if the port is closed (in addition to "disconnected"). 
Sorry I don't know much about ECMAScript naming conventions and syntax.

These additions will give a programmer full control and knowledge if a port is available, and if not, why. There is a bit more typing to do, but no harm done :)

Thanks for your consideration.
Florian

**Comment by cwilso** [comment]
Moved #75 back to v1 consideration, resolving this as duplicate.
