### ISSUE TITLE
MIDI Message Resolution (General Discussion)

### ISSUE THREAD

**Issue by ghost** [WebAudio/web-midi-api#111]
Hi guys, this is more of an implementation question than an issue, so I hope you don't mind.

How precise are MIDI messages likely to be when sent to hardware via Web MIDI? For example, are the messages (timestamps) likely to be quantized to 60Hz frames?

```
// pseudo code (executed once per frame)
while (messageQueue.hasItems) {
  if (messageQueue.item.timestamp <= now) {
    send(messageQueue.item.bytes);
    messageQueue.next();
    continue;
  }
  break;
}
```

I know the events in MIDI files can have incredibly precise timestamps but 60Hz quantization doesn't sound too bad to me. In a 120 BPM MIDI sequence the events would be quantized to 1/30th of a beat. In Reason (the music software) the smallest quantization grid is 1/16th of a beat and that's precise enough for a huge range of musical styles. A quantized MIDI sequence would need to run at about 220 BPM to drop to that resolution.

The reason why I'm asking about this is because I'm prototyping some Web Audio powered virtual MIDI devices to compliment Web MIDI, and the only realistic way to deal with the sending of virtual MIDI messages (the equivalent of `midiOutput.send(bytes,timestamp)`) is to queue the messages and process them in 60Hz bursts (consider a sampler running in an audio worker).

I guess I'm just looking for some feedback here :)

**Comment by cwilso** [comment]
Comparing to Reason's 1/16th beat grid isn't totally correct - you can
usually control the amount of quantization to apply.

Realistically, if you're "auto-quantizing" to ~17ms of error, that's good
enough for a lot of musical styles but too imprecise for others.  You
really can't schedule wakeups to process the messages?

**Comment by ghost** [comment]
Ultimately everything will need to be routed to the `onaudioprocess` event in an audio worker, so I guess I could queue MIDI messages in the audio worker and process them during the `onaudioprocess` event. Doing things that way would allow the messages to be quantized to samples, and that will obviously be a lot more precise. That's actually something I can play around with if I use a script processor node in the meantime.

Out of curiosity, are the buffer sizes in audio workers a fixed (spec'd) length?

**Comment by cwilso** [comment]
The Audio Worker will use the underlying block length - 128 samples.

**Comment by ghost** [comment]
So that means `onaudioprocess` will be called every 3 milliseconds (assuming a 44100 sample rate) if my math is correct, which is more than fast enough. I can simply quantize the MIDI messages to that event. I hope the event object passed to the `onaudioprocess` function is reused by implementations otherwise the GC will probably explode :)

Anyway, I think I know how to handle this now. Thanks for your time Chris, it's appreciated.

**Comment by cwilso** [comment]
I'm confused.  If you're implementing a virtual synth purely in an
AudioWorker, sure, you can handle pre-scheduling in the onaudioprocess.
You REALLY should not be using the onaudioprocess for things that are not
directly related to generating audio, though, because it will drag down
your audio process.

**Comment by ghost** [comment]
It will all be audio generation related, no MIDI message that doesn't directly affect the sound will be sent to an audio worker. The event handler in an audio worker will simply roll through the queued messages and deal with the ones that fall within the 128 sample window... which will probably be zero messages more often than not.

The entire synth/sampler won't be in one audio worker, I will break it down sensibly so the system is more modular with each audio worker handling a relatively small task. That will also reduce the number of MIDI messages each audio worker will need to deal with.

**Comment by cwilso** [comment]
OK.  Sounds like this is resolved, then.
