### ISSUE TITLE
MIDI keyboard's problem

### ISSUE THREAD

**Issue by mattiasalvi** [WebAudio/web-midi-api#113]
Hi,
I'm using the latest version of Chrome with the MIDI flag enabled.
I'm trying to use this web application: http://webaudiodemos.appspot.com/midi-synth/index.html
I can connect my MIDI controller with the synth, so I can see my keyboard in the MIDI_IN list.
When I try to play with the virtual piano I can hear the sound but, if I try to play with my keyboard it doesn't sound.
Have you got any idea to risolve this problem?

Thanks!
Mattia.

**Comment by cwilso** [comment]
Not a web midi api issue; might be a Chrome implementation issue, but haven't had time to check you.
