### ISSUE TITLE
Update spec to reflect addition of maplike<> to WebIDL

### ISSUE THREAD

**Issue by qdot** [WebAudio/web-midi-api#115]
The blink implementation of WebMIDI is now using maplike<> (https://code.google.com/p/chromium/issues/detail?id=432683), and the firefox implementation (https://bugzilla.mozilla.org/show_bug.cgi?id=836897) will most likely use maplike<> once is in place (https://bugzilla.mozilla.org/show_bug.cgi?id=1123516). The spec should reflect this so we don't have discrepancies.

**Comment by yutakahirano** [comment]
The problem is that ReSpec doesn't support maplike right now. https://github.com/w3c/respec/issues/361

**Comment by yutakahirano** [comment]
I'm trying to fix that.

**Comment by toyoshim** [comment]
shall we close this now, or keep it opened until ReSpec support maplike?

**Comment by yutakahirano** [comment]
ReSpec released a new version containing maplike (it was faster than I expected) and I would like to drop the workaround soon.

**Comment by toyoshim** [comment]
great!

**Comment by cwilso** [comment]
Yutaka-san, reference?  I can't find a new release of ReSpec that supports maplike.

**Comment by yutakahirano** [comment]
https://github.com/w3c/respec/pull/408

**Comment by cwilso** [comment]
Done.
