### ISSUE TITLE
MIDIInputMap - Conflict with Maplike?

### ISSUE THREAD

**Issue by ghost** [WebAudio/web-midi-api#118]
In the current Web MIDI spec the [`MIDIInputMap` interface](http://www.w3.org/TR/webmidi/#midiinputmap-interface) appears to conflict with the `maplike` Web IDL definitions that are used by Blink.

Blink's Web IDL file for `MIDIInputMap` looks like this:

```
[
    NoInterfaceObject,
    GarbageCollected,
] interface MIDIInputMap {
    readonly attribute unsigned long size;
    readonly maplike<DOMString, MIDIInput>;
};
```

According to the [Web IDL specification](http://heycam.github.io/webidl/#es-maplike) the use of `maplike` is conflicting with the `MIDIInputMap` interface, for example the `maplike` `values()` function returns an iterator (not a function) and accepts no arguments (not a function).

This is true for the `MIDIOutputMap` interface as well.

Has the Web MIDI specification not been updated to take advantage of ES6 iterable types, or have the Web IDL files been defined incorrectly?

**Comment by toyoshim** [comment]
Is this the same root with #115 ?

**Comment by cwilso** [comment]
Yes.  And last I checked, ReSpec doesn't support maplike yet, so we may have to just stop using respec.

**Comment by ghost** [comment]
Sorry guys, I didn't know this was a duplicate.
