### ISSUE TITLE
close should be allowed on disconnected port

### ISSUE THREAD

**Issue by agoode** [WebAudio/web-midi-api#123]
Part of the contract of MIDIPort#close is releasing system resources:

> explicit close() call enables MIDI applications to ensure other applications can gain access to devices

and

> 6. Close access to the port in the underlying system, and release any blocking resources to the underlying system.

Right now I cannot close() disconnected ports. This means there is no way to release the resources until the port comes back. Additionally, I think that when I close a disconnected port, it should disappear from the list entirely.

**Comment by bome** [comment]
Shouldn't a disconnected port always be closed by the system? Whether it still exists in the list of ports seems like a separate issue.

**Comment by agoode** [comment]
It seems that on CoreMIDI, you really do keep the system handle around while disconnected. On ALSA there is no concept of a disconnected device, so no resources used there. But we will automatically open the device again if it returns. There is currently no way to tell Web MIDI not to bother reconnecting disconnected devices.

**Comment by cwilso** [comment]
The "automatically open the port again if it returns" is the significant bit.

**Comment by bome** [comment]
I'm not convinced the API should auto-open a port if it returns. It complicates the API and a user app can easily implement that feature on its own -- even persistent across restarts of the user app.

**Comment by cwilso** [comment]
I'd disagree.  Otherwise, if I knock out the USB cable for my keyboard, each piece of software has to dynamically respond and re-connect.  Auto-reopen for a port I've already opened is a good idea.

**Comment by toyoshim** [comment]
I prefer automatic close() on device disconnection. It means reconnected device goes not to "opened" state, but to "connected" state.
If an USB cable was mistakenly knocked out, anyway each application should do some sort of re-setup procedures at the next onstatechange event for the reconnection. E.g., the application may want to restore the voice setting, insertion effect configurations, and so on.

We are implementing implicit open() on calling send() or setting onmidievent handlers. So, this does not bother developers working on casual applications. But in this case, we may need to say it explicitly in the spec that if onmidievent handler was set, the reconnected MIDIPort will go to "opened" state automatically.

**Comment by toyoshim** [comment]
> E.g., the application may want to restore the voice setting, insertion effect configurations, and so on.

Here, I assume that if an USB device is disconnected, the device power is also shutdown, and all configurations are reset on the next power on.

**Comment by bome** [comment]
I agree it's a good idea, but I'm concerned that for some applications, it will not be a good idea and cause problems. As you know, MIDI ports are accessed exclusively on some systems, so an auto-open of a forgotten web page will prevent access to that port in other MIDI applications.

Moreover, auto-open is nothing that can only be done by a system implementation. My usual take is to keep high level functionality out of general purpose API's.

**Comment by agoode** [comment]
Yes, if a device goes away, you can't be sure of its state when it returns.

(Although since Web MIDI doesn't provide exclusive access, nothing stops any other application from messing with the device's state at any time.)

I think there is an unanswered question here: what happens to `onmidimessage` handlers during `close()`? This is currently unspecified. Maybe discuss that at issue #79.

**Comment by cwilso** [comment]
@toyoshim "So, this does not bother developers working on casual applications. But in this case, we may need to say it explicitly in the spec that if onmidievent handler was set, the reconnected MIDIPort will go to "opened" state automatically."

That seems like it solves the problem but only for implicit opens; not sure why you wouldn't just persist "open" state too.  But at least the common use cases will be covered as long as you do the implicit open when onmidievent is already set.

**Comment by toyoshim** [comment]
@agoode

Ah, good point.
If we want to define as setting onmidimessage handler will implicitly open the device, we may also want to nullify the handler when close is called. But it does not sound standard way. So, the trigger for the implicit open should not be a state that onmidimessage is being set, but an action to set the handler. So, reconnected device also should go to "connected" state even if onmidimessage handler is set.

**Comment by cwilso** [comment]
Ick.  From a user perspective, that makes it harder.  Every app would need explicit active-connection-listening code to reconnect dropped ports.  I'd rather that be automatic.

If the device needs re-setup, then great - you can listen to the connection events and know that.  But the case of I have to write code that handles re-setting the onmidimessage handler for "dumb" MIDI controller keyboard input - or more likely, I forget to write such code and the user has to reselect the keyboard - seems less than ideal.

I don't think this is high-level functionality; this is akin to "what happens if a transfer is halted when wifi drops out and then comes back".

**Comment by toyoshim** [comment]
If it's ok that close() will reset onmidimessage handler, we can find a good middle ground.
Reconnected device will go "opened" state if onmidimessage handler is set, otherwise, it will go "connected" state.

**Comment by agoode** [comment]
I will capture these suggestions here:
https://gist.github.com/agoode/3338e2dfe49afda36a9b

**Comment by toyoshim** [comment]
@agoode
Thanks. My preference is that opened -> disconnected transition does not reset handlers so that we can preserve the state before/after a reconnection consistently.
