### ISSUE TITLE
Permission exposure: hasMIDIAccess()

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-midi-api#129]
@slightlyoff suggested that we should expose whether MIDI access is already available (i.e. whether a prompt will be fired): 

I'd like to see a `hasMIDIAccess(...)` method added. It doesn't seem possible to know, today, if you are likely to trigger a prompt when calling `requestMIDIAccess(...)` which is likely to confound attempts to build respectful UI.

**Comment by toyoshim** [comment]
https://w3c.github.io/permissions/ Permissions API should be the API for such purpose, and the spec already has a property "midi-sysex". Isn't it enough?

**Comment by agoode** [comment]
That looks perfect for sysex, but it would need the non-sysex case as well.

**Comment by toyoshim** [comment]
non-sysex should be allowed always. Why do you need something for non-sysex case?
IIUC, the original intension is to show some smart UI to ask users to change permission settings if it is disallowed by users. It isn't something to know if the browser supports Web MIDI.
1. requestMIDIAccess({sysex: true}).then(...) => rejected
2. Permissions.query('midi-sysex').then(...) => reason why sysex was rejected, or permitted
3. Show an UI to ask users to enable the permission for the site

The step 1 can be skipped if you do not want to show browser default prompt, e.g. permission infobars on Chrome.

**Comment by agoode** [comment]
Currently the spec suggests prompting in all cases:

http://webaudio.github.io/web-midi-api/#methods

> Requesting MIDI access should prompt the user for access to MIDI devices, particularly if system exclusive access is requested.

The spec would need to change if you want the behavior you suggest. (I have no opinion at this time on which way it should be.)

**Comment by toyoshim** [comment]
Hum. The spec allows prompting even for non-sysex cases, but it is not mandatory.
Even so, adding "midi" to Permissions API looks a right solution here.

**Comment by cwilso** [comment]
the requestAccess(...)/hasAccess(...) pairing is intended to be a standard
pattern, is it not @slightlyoff?  Otherwise yes, we'd need a pair of
permissions (Permission.query('midi') and Permission.query('midi-sysex')) -
but that won't scale well if we have any future options put in the
requestMIDIAccess options object (e.g. if we do a MIDI-MC to get permission
to use MIDI Machine Control (play/stop/ff/rw/rec/etc), which are
technically a subset of sysex (but a "safe" one, perhaps?)

**Comment by toyoshim** [comment]
I grep-ed request\* method under blink modules directory, and find some examples.

https://dvcs.w3.org/hg/notifications/raw-file/tip/Overview.html
https://dvcs.w3.org/hg/quota/raw-file/tip/Overview.html
http://webbluetoothcg.github.io/web-bluetooth/

But, they also do not have has\* method for now.

I do not think using Permissions API does not scale. The cost to add new item to the spec and implementation is almost same, but only difference is where we have.

**Comment by toyoshim** [comment]
I'm +1 on Permissions.query("midi", optional Dictionary) style that Chris suggested in a separate discussion.

**Comment by qdot** [comment]
Was just doing permissions implementation for firefox and ran into this. I ended up translating the spec as saying "make both a midi and midi-sysex permission" and went that direction, but also ran into another issue...

_"Prompt the user in a user-agent-specific manner for permission to provide the entry script's origin with a MIDIAccess object representing control over user's MIDI devices. This prompt may be contingent upon whether system exclusive support was requested, and may allow the user to enable or disable that access."_

So I translated this as "The site can ask for MIDI with Sysex permissions, but the user can say that the site can have MIDI access, but without sysex permissions, and that will still be valid".

But then later in the algorithm:

_"failure: Let error be a new DOMException. This exception's .name should be "SecurityError" if the user or their security settings denied the application from creating a MIDIAccess instance with the requested options"_

Which makes it sound like an all or nothing thing, so my understanding is that these conflict?

**Comment by qdot** [comment]
FWIW, I considered midi-sysex to be a superset of midi permission, so if midi-sysex permission was given, midi was also given. So it seems like scaling isn't quite as big of an issue here since permissions are stackable.

**Comment by cwilso** [comment]
Keep in mind there is also (already) the suggestion of a software synth Option, and likely to be more.  I think we should go with hasMIDIAccess, or we should explicitly deconstruct the Options into Permissions.  Thoughts?

**Comment by toyoshim** [comment]
Do we still need hasMIDIAccess method?
Permissions API already supports "midi" and we can pass MIDIOptions as a PermissionDescriptor.
https://w3c.github.io/permissions/#idl-def-MidiPermissionDescriptor

**Comment by cwilso** [comment]
Ooo, sounds good.  Although we'll need to add "software" in that permissions descriptor, too.

**Comment by adam-lynch** [comment]
It seems to me that the permission API always returns `granted` (in Chrome), even if you've clicked "Block".  Go to https://ryoyakawai.github.io/smfplayer/, block the permission, then run `navigator.permissions.query({ name: 'midi' }).then((res)=>console.log(res))` in the console.

![screen shot 2018-02-17 at 11 14 13](https://user-images.githubusercontent.com/1427241/36340425-731ec220-13d4-11e8-9adb-6277b144ff56.png)

**Comment by adam-lynch** [comment]
ahh.... the demo uses sysex so it needs to be `navigator.permissions.query({ name: 'midi', sysex: true })`... nevermind! :slightly_smiling_face:

**Comment by cwilso** [comment]
I believe this issue is resolved at this point.
