### ISSUE TITLE
Editorial issues on MIDIPort.open() algorithm

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#131]
1. The label for the step 8 is "success" and one for the step 10 is "opened" for now. But swapped labels looks more reasonable because the step 8 is used only for "open", but step 10 is used for both "open" and "pending".
2. In the step 8, "opened" should be "open".
3. In the step 12, it says that `or "InvalidStateError" if the port is disconnected`. But, should it go back to the step 6 if the device is disconnected on the way to open the device?

**Comment by toyoshim** [comment]
Thank you for quick fixes, but still there are some nits.
1. is not fixed in the #131

"state" should be "connection" or connection state in the step 4, 5, and 8. The second "state" should be "connection" in the step 6.

**Comment by cwilso** [comment]
Updated.  I'm not sure what you mean by "1. is not fixed" - I swapped the state labels, but then realized it was unnecessary to label the first state (there are no jumps to that state), so removed the "open" state.

**Comment by toyoshim** [comment]
Oh, I meant 2 was not fixed.

**Comment by cwilso** [comment]
Ah.  Then I found and fixed it in that last commit.  :)
