### ISSUE TITLE
Lifetime of MIDIAccess and MIDIPort is still vague

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#134]
Since MIDIAccess and MIDIPort inherit EventTarget they could survive even after all references from JavaScript were released.

Current Blink implementation:
If all references from JavaScript were released, it could be GCed.

New Blink implementation (planned):
Even if all references from JavaScript were released, it will survive GC,
 `MIDIAccess` if onstatechange handler is set.
 `MIDIPort` If connection is not "closed".
and handler will be invoked on corresponding events.

**Comment by cwilso** [comment]
MIDIAccess I understand.  On MIDIPort, if the connect is left open but it is a MIDIOutputPort, as long as the onstatechange handler isn't set it can be GCed, yes?  And similarly, a MIDIInputPort should be able to be GCed if the event handlers are nulled first, yes?

**Comment by toyoshim** [comment]
Ah, you are right. If we do not have any reference from JavaScript, we do not have any chance to close the port any more. So, we should make it possible to GC them if no handlers are set.

**Comment by cwilso** [comment]
OK.  Seems like the spec needs an update describing this and recommending best practice, then.
