### ISSUE TITLE
Web Midi Logo

### ISSUE THREAD

**Issue by skratchdot** [WebAudio/web-midi-api#137]
See the following thread: https://lists.w3.org/Archives/Public/public-audio/2015AprJun/0018.html

**Comment by skratchdot** [comment]
I submitted pull request #138 as a starting point.  I'm not a designer, so this is bad (just a combination of the midi logo, and some text), but I figured I'd get a folder and a readme started.

**Comment by cwilso** [comment]
Not part of the spec, so closing issue.  Discussion continues on the list.
