### ISSUE TITLE
Changes to the Web MIDI API Mandate?

### ISSUE THREAD

**Issue by notator** [WebAudio/web-midi-api#153]
The Abstract at the top of the current Working Draft Web MIDI API [1] says (my emphasis):

> [...] The Web MIDI API is intended to enable direct access to devices that respond to MIDI - external synthesizers or lighting systems, for example, **or even the software synthesizers that are built in to many common operating systems**.

We now know that accessing "the software synthesizers that are built in to many common operating systems" poses an unacceptable security risk. So they should be deleted from the preamble.

Working on my posting for public-audio-dev@w3.org (see issue #150) has meant thinking "outside the system". One possibility I can now see is that the Web MIDI API's mandate could be extended to include standards (interfaces) relating specifically to software Web MIDI synthesizers. Such standards would not affect browser implementations of the API since they only deal with hardware synths.

Would changing the preamble to include software synthesizers need permission from the W3C?

It might be better for me to post my (currently off-mandate) thoughts on Web MIDI Synths here after all. What do you think?

[1] http://webaudio.github.io/web-midi-api/

**Comment by cwilso** [comment]
Removed reference.  Let's keep #150 open as we decide how to deal with this.
