### ISSUE TITLE
Windows, sending long SysEx messages fails, works on Mac

### ISSUE THREAD

**Issue by andrejhronco** [WebAudio/web-midi-api#157]
I have an application i'm working on that sends sysex to a midi device. SysEx smaller than 60KB works but anything longer fails without any messages or debugging help.

I've been perusing the Chromium source and found this pertinent file: midi_manager_win.cc which has this implementation note:

> `Note for built-in USB-MIDI driver:
> From an observation on Windows 7/8.1 with a USB-MIDI keyboard,
> midiOutLongMsg() will be always blocked. Sending 64 bytes or less data
> takes roughly 300 usecs. Sending 2048 bytes or more data takes roughly
> |message.size() / (75 * 1024)| secs in practice. Here we put 60 KB size
> limit on SysEx message, with hoping that midiOutLongMsg will be blocked at
> most 1 sec or so with a typical USB-MIDI device.`

I'm not understanding the reason and/or implied solution regarding the 'midiOutLongMsg' API. It seems like the large message starts sending and then hangs, i'm assuming when it has reached 60KB, but midiOutLongMsg doesn't become unblocked after 1s.

Additionally, I'm testing this on a Windows 10 machine.

How can I successfully send longer sysEx messages to a MIDI Device on Windows?

**Comment by cwilso** [comment]
This sounds like just a bug report to Chromium.

**Comment by andrejhronco** [comment]
Thanks Chris,
I've filed a bug report to Chromium here: [issue 575334](https://code.google.com/p/chromium/issues/detail?id=575334)
