### ISSUE TITLE
implementation tracking: WebMIDI in Firefox and Edge

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-midi-api#161]
Raised in plenary session at WAC2016. @padenot mentioned ongoing implementation in Firefox, not yet shipped. Edge status unknown. This is just to track the multiple implementations (after Chrome, which has shipped).

**Comment by padenot** [comment]
The tracking bug for Firefox is https://bugzilla.mozilla.org/show_bug.cgi?id=836897.

**Comment by cwilso** [comment]
BTW, I'm not really sure why we have this as a spec issue?  I'd rather not keep spurious issues unless we really need them.  A Google search for "web midi firefox" turns up the relevant link as top link, so not sure how necessary this is?
