### ISSUE TITLE
MIDIMessageEvent could be merged to another existing Event.

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#165]
This is raised in the blink-dev thread for `MIDIMessageEvent.receivedTime` deprecation.

Actually, once we remove `receivedTime`, `MIDIMessageEvent` is very similar to [`BlobEvent`](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent) or [`MessageEvent`](https://html.spec.whatwg.org/multipage/comms.html#messageevent).

`BlobEvent` has `data` attribute, but only difference is the type is not `ArrayBuffer`, but `Blob`. So, to be consistent with `BlobEvent`, our event could be `ArrayBufferEvent`.

`MessageEvent` looks designed as a more general-purpose event. It has `data` attribute, and it is defined as `any`. In the real use case, it could be one of `DOMString`, `Blob`, and `ArrayBuffer` for `WebSocket` and `RTCDataChannel`, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent).

The `MessageEvent` has `origin`, `ports`, and `source` attributes to be used for remote communication. This isn't needed at this point, but would be useful when we expand the API to register JS based virtual ports running on Worklets.

Any thoughts?

**Comment by toyoshim** [comment]
One concern is event name. Now MIDIInput has onmidimessage attribute, and 'midimessage' can be subscribed through AddEventListener method. If we change the Event class to use here, we may need to consider changing the attribute and event name too? That breaks compatibility again :(

**Comment by cwilso** [comment]
If we can still use "midimessage" as the attribute/event name, I'd be okay with using MessageEvent, except I wonder if we should be putting the port on the event object?  And "ports" on messageevent is confusing, since it might get confused with the MIDIPort associated with the message?

**Comment by cwilso** [comment]
Ask for TAG feedback.

**Comment by toyoshim** [comment]
Let's keep this thread open as if we merge the event, names will be conflicted or existing names are too general. If we want to fix this problem, it will break compatibility.

**Comment by hoch** [comment]
2023 TPAC Audio WG Discussion:
This implies a substantive change of the IDL and also significantly limits the future extensibility/flexibility of this interface. The WG decided not to purse this idea.
