### ISSUE TITLE
MIDIPort.open disappears from the IDL in the processed spec

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#166]
This is editorial issue, but in the MIDIPort IDL definition, open method seems to disappear.
http://webaudio.github.io/web-midi-api/#idl-def-MIDIPort

Some lines from line 448 in the raw index.html seems to be the descriptions for the open method, but for some reasons, it looks not shown in the processed spec page.

**Comment by cwilso** [comment]
This appears to be resolved.  Can you verify?
