### ISSUE TITLE
MIDIMessageEventInit and MIDIConnectionEventInit members should be required

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-midi-api#168]
http://webaudio.github.io/web-midi-api/#MIDIMessageEvent
http://webaudio.github.io/web-midi-api/#MIDIConnectionEvent

Currently, the init dicts for the event constructors are optional, so `new MIDIConnectionEvent('type')` should work per spec. But the `port` attribute then couldn't be anything other than null, and yet it's not nullable.

The way to fix this is to make the init dicts non-optional and to make the members required, e.g.:

``` WebIDL
[Constructor(DOMString type, MIDIConnectionEventInit eventInitDict)]
interface MIDIConnectionEvent : Event {
    readonly        attribute MIDIPort port;
};

dictionary MIDIConnectionEventInit : EventInit {
             required MIDIPort port;
};
```

The only other option is to make the `port` attribute nullable, which would be silly.

**Comment by foolip** [comment]
Friendly ping :) Blink's IDL is out of sync with the spec here and we'd like to fix it, but ideally not before the spec is fixed.

**Comment by cwilso** [comment]
I think that #207 has obviated this, but I'm going to keep them both open until I've fixed.

**Comment by foolip** [comment]
Constructor operations should be unrelated to this, unless one makes drive-by fixes when fixing that of course.

This issue could be summarized as the difference between the IDL in spec and Blink:
https://webaudio.github.io/web-midi-api/#MIDIConnectionEventInit
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webmidi/midi_connection_event_init.idl;l=8;drc=0aee4434a4dba42a42abaea9bfbc0cd196a63bc1

It looks like the nullability is the only remaining difference, and just making the member nullable in the spec would probably be the most pragmatic here.
