### ISSUE TITLE
Use <pre class=idl> for IDL blocks

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-midi-api#170]
A friendly request. In https://github.com/mdittmer/web-apis @mdittmer is working on tooling for extracting the IDL from specs linked to from Chromium's source code, for the purpose of comparing the IDLs. This will hopefully be a powerful tool for avoiding accidental differences.

In order to avoid having to use a real browser to scrape the IDL, it's useful if a `<pre class=idl>` block is used. This is one spec that Mark found relying on ReSpec's `<dl class=pre>` feature.

Note that this is already a ReSpec warning: "Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://github.com/w3c/respec/wiki/User's-Guide#webidl-support"

**Comment by marcoscaceres** [comment]
Working on this...
