### ISSUE TITLE
Bad references

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#172]
The references in the spec are way obsolete - particularly in the deps section.

**Comment by eyqs** [comment]
The current link to http://www.midi.org/techspecs/index.php redirects too many times, and its URL should be updated to https://www.midi.org/specifications instead.

**Comment by svgeesus** [comment]
I updated specref so it has a good, correct ref for MIDI. So that should fix this issue. [MIDI] should just work.
https://github.com/tobie/specref/pull/364
