### ISSUE TITLE
Examples could be modernized

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#173]
The examples do odd things in strange ways... like use .forEach to map to elements, etc. 

They could be much improved.

**Comment by toyoshim** [comment]
keep this open for update in the future, and may work together with #174

**Comment by mjwilson-google** [comment]
See also #230

**Comment by mjwilson-google** [comment]
The examples are now in the explainer.  Let's use this issue to track updating them.

**Comment by mjwilson-google** [comment]
There are still `.forEach` instances in the main body of the spec, so I will move this back to the CR milestone.

**Comment by mjwilson-google** [comment]
Specifically, in sections:
https://webaudio.github.io/web-midi-api/#MIDIInputMap
https://webaudio.github.io/web-midi-api/#MIDIOutputMap

And in the explainer here:
https://github.com/WebAudio/web-midi-api/blob/gh-pages/explainer.md#handling-midi-input

I'm not sure what other style issues we need to resolve.

**Comment by mjwilson-google** [comment]
As noted in the linked PR, all the examples are now in the non-normative explainer.  I removed `.forEach` and think that's enough for CR review; if there are additional updates that should be done please file new issues.  The examples can be fixed in the explainer without having to modify the spec.
