### ISSUE TITLE
Example section should move to explainer 

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#174]
We should create an explainer for the examples. They bloat the spec quite a bit at the end, and will generally need updating as ES improves (e.g., using async/await syntax and functional programming style for this API).

**Comment by toyoshim** [comment]
discussed at tpac. let's keep open for update in the future

**Comment by mjwilson-google** [comment]
Done, the other example fixing issues can be applied to the explainer now.
