### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Pomax** [WebAudio/web-midi-api#197]
Hiya, I was reading through https://github.com/mozilla/standards-positions/issues/58 and noticed the objection to implementing being "it's still a draft" (which is a weird argument for a browser that has traditionally implemented things even before they were drafts, to get them to become real, but that's a discussion for another time and place). So I figured I'd look up what the expected roadmap for this spec was, but I can't seem to find anything that shows when it started, which milestones it was/is aiming for, and when there is the (optimisitic, of course) expectation/hope to get the draft accepted as spec and what work was/is required to get it there?

(basically: lots of folk would _love_ to finally get webmidi broadly supported, but no one with the power to implement it outside of chrome seems to care in the slightest: should anyone expect this draft to ever make it to spec, so that we can request browser makers to implement a spec, instead of hiding behind "it's just a draft", or is it something that's getting bashed more than it's getting love and if it does land it'll be on the timescale of MIDI itself?)

**Comment by cpenny42** [comment]
Relevant Bugzilla link:

https://bugzilla.mozilla.org/show_bug.cgi?id=836897

The discussion started 6 years ago 🙄

**Comment by bome** [comment]
AFAIK, a web draft spec can only become a standard if it's implemented by at least 2 independent browsers. Which makes the argument "it's still a draft" even less compelling.

**Comment by cpenny42** [comment]
Also WebMIDI is implemented in Opera and Chrome: https://caniuse.com/#feat=midi

**Comment by zulaica** [comment]
Opera is effectively Chrome under the hood so I don't believe that would qualify as "two" (and Edge is going that route). The Mozilla or Safari teams would need to be on board.

**Comment by toyoshim** [comment]
notes from a TPAC discussion.
We'll keep this issue open for a while and wait for mozilla's standard's position update.

**Comment by mjwilson-google** [comment]
The current Audio Working Group Charter has a timeline that includes taking Web MIDI to W3C Recommendation:
https://www.w3.org/2022/02/audio-2022.html

This is possible thanks to Mozilla's implementation and positive standards position (https://mozilla.github.io/standards-positions/#webmidi)!

I am now an editor of this specification, and hope to guide it with the support of the community and Audio Working Group to full Recommendation status.  While we may not make the CR deadline in the charter (which is just over two weeks from now), the Q3 2025 target for Recommendation seems like it should be achievable.  If the Audio Working Group recharters then I expect we will post an updated timeline in the new charter.

I will close this issue, but please feel free to discuss more or reopen if anything is unclear.
