### ISSUE TITLE
Windows MIDI Port Disconnect / Connect Events Lock Up Chrome

### ISSUE THREAD

**Issue by andrejhronco** [WebAudio/web-midi-api#198]
When manually disconnecting / connecting a device more than a couple of times, statechange events stop emitting and afterwards, refreshing the browser causes it to become unresponsive entirely.
A variation on this issue is that upon disconnection, no events are emitted, but when reconnecting both disconnected and connected events are emitted in sequence. 

This is using the default MIDI (on Windows 10, WinRT MIDI default/disabled). 
With WinRT (Windows 10) enabled, statechange events seem to emit consistently.

To reproduce, paste this into the console and manually reconnect / disconnect the device.  
`navigator.requestMIDIAccess({sysex: true}).then(access => access.onstatechange = (event) => console.log('state change', event))`

I think there was a similar issue a few years ago that I can't seem to find.

**Comment by toyoshim** [comment]
Hi, here is a place to discuss the API spec.
Can you use crbug.com for the Chrome specific implementation issue?
Probably crbug.com/924524 is the one that might be related.
