### ISSUE TITLE
Any way to access Web Midi Access in chrome without SSL certificate?

### ISSUE THREAD

**Issue by Tortenrandband** [WebAudio/web-midi-api#208]
Hi,
I've been using chromes Web Midi for a small drawing app to change colors
and i'm rather sad that it stopped working. :(
http://www.h3nk.com/midi.htm

Is there a setting to activate it without buying a certificate?

Setting flag chrome://flags/#use-winrt-midi-api to enabled didn't help.

**Comment by espoelstra** [comment]
You could use LetsEncrypt to get a free certificate for your site or if you had your site set up as a GitHub Pages site you can get SSL for free from GitHub as part of that Pages setup.

**Comment by toyoshim** [comment]
Web MIDI interfaces defined in the spec https://webaudio.github.io/web-midi-api/ requires SecureContext (See https://heycam.github.io/webidl/#SecureContext).

See https://www.chromium.org/Home/chromium-security/owp#TOC-Secure-Contexts to know what is secure context in the chromium implementation.
