### ISSUE TITLE
Web MIDI does not detect multiple devices in Windows

### ISSUE THREAD

**Issue by tyzjames** [WebAudio/web-midi-api#217]
When connecting multiple devices of the same product in Windows, WebMIDI only returns one device in the iterator. Seems like the issue is tied to the device USB Product ID. I changed the Product ID for one device (I have 2 of the same device connected), and it identifies both devices fine.

`
for (let input = this.inputs.next(); input && !input.done; input = this.inputs.next()) {
            console.log('Inputs', input);
}
`

This issue only exists for Windows Chrome. It works fine on MacOS.

**Comment by rektide** [comment]
This is an implementation not a specification bug.

I found [this document](https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en) for filing a bug in Chrome. There is also a chromium bug tracker you might use. @tyzjames, please kindly close this issue, as it's not related to the specification of WebMIDI.

**Comment by cwilso** [comment]
Yep, not a Web MIDI bug; please file as Chromium bug.
