### ISSUE TITLE
Outputs array empty on Safari

### ISSUE THREAD

**Issue by chrissysemens** [WebAudio/web-midi-api#226]
Hey,

I've just tried to use the react starter example and was getting an empty outputs array logging. I've opened the same app in chrome and the outputs array logs three devices:

Its Safari v15 on Mac OS Big Sur
![Screenshot 2021-12-14 at 16 51 55](https://user-images.githubusercontent.com/46443589/146042855-d3a436b9-2f9e-4a71-9c8c-540029ded491.png)

![Screenshot 2021-12-14 at 16 52 32](https://user-images.githubusercontent.com/46443589/146042991-394299c0-9305-4da6-95c4-606795216da8.png)

Happy playing Chrome for now but thought I'd let you guys know.

**Comment by djipco** [comment]
This is the GitHub repo for the **Web MIDI API** specification. I'm guessing you are looking for the WEBMIDI.js library repo which is available at: https://github.com/djipco/webmidi 😉 You can ask your question over there!

By the way, [Apple decided](https://webkit.org/tracking-prevention/) not to support the Web MIDI API (and several other APIs) over fingerprinting concerns.

**Comment by cwilso** [comment]
Yep, this is a Safari bug report, or more precisely, a feature request.
