### ISSUE TITLE
Hardware disconnect froze Chrome

### ISSUE THREAD

**Issue by DDS9** [WebAudio/web-midi-api#228]
Testing the robustness of working code, I yanked a MIDI Port device USB cable from the PC, and Chrome froze up completely, needing a hard process termination via Task Manager.  

I was expecting a "port-change" event with connection information.  

Is it possible to add some grace to the core WebMIDI code to cope with this kind of eventuality?

Note that in my test case, only one event listener was hooked in, into a working MIDI input.  It was a second and unused USB MIDI port device which was unplugged from the MIDI ecosystem, which caused the lock up.

**Comment by djipco** [comment]
I believe the right place to report bugs found in Google Chrome is the [Chromium Bug Tracker](https://bugs.chromium.org/p/chromium/issues/list). You can file your issue over there.

This repo is for the [Web MIDI API specification](https://webaudio.github.io/web-midi-api/).

**Comment by DDS9** [comment]
Interesting distinction.

Added to Chromium Bug Tracker.

**Comment by hoch** [comment]
@DDS9 Do you have a link to the bug that you filed? (Also closing this because it's not a spec bug)
