### ISSUE TITLE
MIDI-related terms in terminology section are not defined in the MIDI reference

### ISSUE THREAD

**Issue by mjwilson-google** [WebAudio/web-midi-api#244]
The terminology section (https://webaudio.github.io/web-midi-api/#terminology) currently says the following:

"The terms MIDI, MIDI device, MIDI input port, MIDI output port, MIDI interface, MIDI message, MIDI System Real-Time message and system exclusive are defined in [[MIDI](https://webaudio.github.io/web-midi-api/#bib-midi)]."

In addition to lacking a definition of a "valid MIDI message" (#164), there are several other issues with this section:

- "MIDI device" is not really defined in the MIDI specification, although the meaning could be inferred from the text
  - Proposal: This is probably ok to leave as-is
- "MIDI input port" and "MIDI output port" are called "MIDI In port" (or sometimes "MIDI IN port") and "MIDI Out port" in the MIDI specification, and are first defined in terms of electrical diagrams which isn't how the terms are used in the Web MIDI specification
  - Proposal: Redefine these terms in the Web MIDI spec based on the definitions of "MIDI In port" and "MIDI Out port" defined in the MIDI specification
- "MIDI interface" isn't really defined in the MIDI specification; there is a definition of the hardware interface but that is not how we use the term in the Web MIDI specification
  - Proposal: This is a bit trickier; we seem to use the term "MIDI interface" to refer to things the OS layer presents.  So maybe we need to find different references for this term, or to define the term directly in the Web MIDI specification.
- [DONE] "MIDI System Real-Time message" is written in various ways in the MIDI specification: "Real Time", "Real-Time", "System Real-Time", "System Real Time", and sometimes with "messages" attached and sometimes without; it seems like the version with the space ("Real Time") is more common than the version with the hyphen ("Real-Time")
  - Proposal: Let's make the linked term "System Real Time" since the MIDI specification chapter that talks about these messages doesn't have a hyphen.  The Web MIDI spec only references these messages in [one section](https://webaudio.github.io/web-midi-api/#MIDIInput), so it's not a large change.
- [DONE] "system exclusive" is written "System Exclusive" in the MIDI specification
  - Proposal: Update the name to "System Exclusive" to match the MIDI spec
- [DONE] Most of the definitions are not linked from the rest of the spec text
  - Proposal: Link the first usage of each term in each section that uses it (edit: actually, link all usages)
- [DONE] The MIDI spec link is out of date since midi.org changed their website
  - Proposal: Update the bibliography in https://github.com/tobie/specref/blob/main/refs/biblio.json

**Comment by mjwilson-google** [comment]
Referring to other specs, it seems like it's probably better to link the definitions every time they are used instead of just the first usage in each section.  That part can also be done right before applying for CR status.

**Comment by svgeesus** [comment]
> * (preferred) https://www.midi.org/specifications/midi1-specifications/midi-1-0-core-specifications/midi-1-0-detailed-specification-2

If you are not logged in to midi.org, that gives

> Oops! That page can’t be found.

Maybe https://midi.org/midi-1-0

**Comment by mjwilson-google** [comment]
> Maybe https://midi.org/midi-1-0

We recently changed it to https://midi.org/midi-1-0-core-specifications -- sorry about the stale info in the description.  I will edit it.

**Comment by mjwilson-google** [comment]
There are four terms left from the original issue statement.

"MIDI device", "MIDI input port", and "MIDI output port"  are probably clear enough from the reference that we don't need to do anything about them.

"MIDI interface" is the only remaining part of this issue that might need some clarification.  It's arguable that, since MIDI stands for Musical Instrument Digital Interface, the entire MIDI spec describes a "MIDI Interface".  In the current Web MIDI spec the "MIDI Interface" term is mostly used in the privacy and security sections, where I think it's reasonably clear from context.

So, I think this issue can be closed without further changes to the spec.  Since I raised the issue, I will make the call to close it and we can file new issues if specific definitions are confusing during the wide review stage.
