### ISSUE TITLE
MIDI 1.0 spec link is dead

### ISSUE THREAD

**Issue by dead-claudia** [WebAudio/web-midi-api#266]
Location: https://webaudio.github.io/web-midi-api/#bib-midi

Current link: https://www.midi.org/specifications/item/the-midi-1-0-specification

Most recent working archive link: https://web.archive.org/web/20230925092419/https://midi.org/specifications/item/the-midi-1-0-specification/

Did some digging, and they moved everything to various subpages of https://midi.org/midi-1-0. In general, they collected all their specs to https://midi.org/specs, including their file format specs and MIDI 2.0.

**Comment by mjwilson-google** [comment]
Thanks for the report!

As noted in #244 we can't change that in this repo.  I think the line at time of writing is here:
https://github.com/tobie/specref/blob/main/refs/biblio.json#L2386

The updated links I wrote in #244 are also dead now.  I don't know what the best stable link to this document would be.

Eventually I will try to get this updated in specref, but if you have time and are interested please feel free to file a bug / PR against specref and report here.

**Comment by mjwilson-google** [comment]
@cwilso has filed a PR to fix this: https://github.com/tobie/specref/pull/814

**Comment by mjwilson-google** [comment]
The fix was rolled out and is showing up in the Editor's Draft now.  It should roll out to the Working Draft along with the next commit we make.  I will close this issue; thanks @dead-claudia for raising this issue and @cwilso for the fix!
