### ISSUE TITLE
MIDI timer

### ISSUE THREAD

**Issue by notator** [WebAudio/web-midi-api#44]
We are using currently using DomHighResTimeStamp, and there is a note in section 8.1:

> The DOM4 Event object has a timeStamp member in the event object that will be filled out
> with the current time, but that it is lower precision (DOMTimeStamp is defined as an
> integer number of milliseconds), has a different zero reference (DOMTimeSTamp is the
> number of milliseconds that has passed since 00:00:00 UTC on 1 January 1970), and
> therefore is less suitable for MIDI applications. 

I'm writing a MIDI application which uses millisecond resolution for timing. It is simply much easier to use integral values for event timing, because one does't have to allow for the rounding errors which happen when adding floating point values  (DOMHighResTimeStamp).
And the use of setTimeout() means that higher resolution is actually unnecessary, so I'm always rounding (DOMHighResTimeStamp) Event timings to integral milliseconds.

Audio obviously needs a higher precision timestamp than MIDI, but it would be more convenient/efficient for MIDI applications to deal with integral milliseconds.

It would probably help, in some applications, if Audio and MIDI shared the same zero reference, so do we need to define and use an integral millisecond timer with the same zero reference as DomHighResTimeStamp?

**Comment by jussi-kalliokoski** [comment]
Hi James,

If you're worried about rounding errors (not sure where you'd have a
problem with them with the Web MIDI API), casting a DOMHighResTimeStamp to
an integer ( `Math.floor(myMidiEvent.receivedTime)` ) will... well... make
it an integer, so you don't have to worry about that. And even then, you
get advantage from DOMHRTF because integer overflow is several decades
further away than with DOMTimeStamp. ;) I don't see that as a very serious
issue for now, though, at least not in particular with the Web MIDI API.

If you need to sync an AudioContext's clock with DOMHRTF, you can just get
the offset:

``` javascript

/* calculate offsets for syncing with clocks */
var offsetMilliseconds = ctx.currentTime() * 1000 - performance.now()
var offsetSeconds = offsetMilliseconds / 1000

/* play a Web Audio API sample when you receive a midi event */
output.onmessage = function (e) {
  var sample = ctx.createBufferSource()
  /* ... */
  mySample.start(e.receivedTime / 1000 - offsetSeconds)
}

```

Cheers,
Jussi

**Comment by notator** [comment]
Hi Jussi,

Its just that I can't think of _any_ MIDI application that would need more than millisecond resolution, so I don't really see why they should be using a floating point timer and having to go through all those rigmaroles.
I can live with the current situation, of course, but think it could be improved. :-)

best,
James

**Comment by jussi-kalliokoski** [comment]
@notator I understand. Allow me to open up the reasoning behind choosing DOMHRTF for a bit... We could have chosen to go with a custom clock tailored for MIDI purposes, but instead I believe there are already too many different clocks (on the web platform) to keep track of and adding our own would have very little positive value, but a lot of negative value (added complexity, and [added feature cost](http://wiki.whatwg.org/wiki/FAQ#Where.27s_the_harm_in_adding.E2.80.94)). Therefore I think it was most reasonable to pick the clock that behaves closest to our needs, i.e. is accurate and simple. DOMHRTF is designed to be exactly that.

> having to go through all those rigmaroles

What exactly are you referring to?

**Comment by notator** [comment]
Okay, I think I'm convinced.

The "added feature cost" argument (against having a new timer) is pretty strong.

Your second example:

``` javascript
/* play a Web Audio API sample when you receive a midi event */
output.onmessage = function (e) {
  var sample = ctx.createBufferSource()
  /* ... */
  mySample.start(e.receivedTime / 1000 - offsetSeconds)
}
```

could be simplified if e.received time was an integral number of milliseconds and offsetMilliseconds was used instead of offsetSeconds.
But what if an Audio application wanted to fire a MIDI event in the middle of some envelope? That's a situation I hadn't thought of when I raised this issue.

Back in my own application, I'm still wanting to use whole milliseconds all the time.
Actually, I'm not using

``` javascript
e.receivedTime
```

at all. Is it redundant? Is it an unnecessary "added feature"? :-) All I do is call

``` javascript
window.performance.now()
```

in the handling routine when the message arrives...

As a naive javascript programmer I'm now asking myself whether it would be better to use

``` javascript
now = Math.round(window.performance.now());
```

or

``` javascript
now = window.performance.now().toFixed();
```

It probably doesn't matter much, but I'm now wondering if there ought to be an informative "recommended practices" section...

Rigmaroles: Those are all the things one has to think about (and program) when the unit of time is inconsistent. Its easiest to ensure consistency when the time is set. :-)

By the way, example 9.5 contains a couple of errors:
1. e.timestamp should be renamed e.receivedTime (if it exists at all).
2. midi, (the "// global MIDIAccess object") is never used, and should be deleted
Maybe this would be a good time to raise a separate issue about section 9. I think Marcos suggested that all the examples should be turned into closures, to avoid any discussion about global variables...

best,
James

**Comment by jussi-kalliokoski** [comment]
> Back in my own application, I'm still wanting to use whole milliseconds all the time.
> Actually, I'm not using
> 
> e.receivedTime
> 
> at all. Is it redundant? Is it an unnecessary "added feature"? :-) All I do is call
> 
> window.performance.now()
> 
> in the handling routine when the message arrives...
> 
> As a naive javascript programmer I'm now asking myself whether it would be better to use
> 
> now = Math.round(window.performance.now());
> 
> or
> 
> now = window.performance.now().toFixed();
> 
> It probably doesn't matter much, but I'm now wondering if there ought to be an informative "recommended practices" section...

Since you ask about recommended practices, I would recommend against that (using performance.now() instead of e.receivedTime). Most of the time, it will work as expected, but for example if your application is under stress, and records MIDI input, performance.now() is likely to start differing from the actual received time (e.receivedTime). The MIDIEvent's receivedTime attribute is not redundant by any means, in fact it's crucial to building reliable MIDI applications.

As for flooring, I'm still not convinced why you need it, but since you ask, I usually floor in JS like this:

``` javascript

var rt = ~~e.receivedTime

```

But that assumes the number fits a signed 32-bit integer (usually when I need to floor, it does). If the number might overflow that, I use Math.floor(). For example:

``` javascript

~~(15.7) // 15
var bignum = Math.pow(2, 33) + 0.5 // 8589934592.5
~~(bignum) // 0 (Probably not what we wanted)
Math.floor(bignum) // 8589934592

```

Number#toFixed() on the other hand returns a string so you probably shouldn't use that unless you want to display a number to a user in a fixed point format.

> 1. e.timestamp should be renamed e.receivedTime (if it exists at all).

Hmm, yeah, the code examples are out of date now, I actually just noticed today that the timeStamp had been renamed to receivedTime. ^^ We'll fix them.

**Comment by notator** [comment]
Thanks for that.
I'm changing my code to use e.receivedTime. Will have another think about whether I really, really need to use integral milliseconds, and use Math.floor() if I do.

best,
James

**Comment by notator** [comment]
I'm using integral milliseconds because my application is recording and saving Standard MIDI Files -- which don't contain floating point millisecond timings.

Its possible to set SMFs up so that their timings are whole milliseconds, so that's what I'm doing. It would be possible to use fractions of a millisecond, but that seems like overkill (especially given the setTimeout() problematic), but _some_ kind of conversion from floating point milliseconds is going to have to be done if one wants to save an SMF.

Users of my application can trigger the sending of hundreds of pre-constructed MIDI messages using one input Event, and I don't need floating point values anywhere, so my instinct (maybe wrong in javascript on today's fast processors) was to round the timings on input, and use "int"s everywhere. If I've got millions of messages in memory, waiting to be sent, it would be nice to keep their memory usage down!
If my original instinct was wrong, and there's no way to keep memory usage down by using an "int" instead of a "double", and rounding the millions of double timings takes next to no time, it would probably be better to do the rounding as part of saving the SMF rather than at recording time. Thoughts?

Interestingly, this provides an argument in favour of floating point milliseconds:
Since SMFs have no standard time unit, anyone using one as _input_ will first have to convert its timings to floating point milliseconds. :-)

Another question: In section 8, if MIDIEvent is only ever going to be used as an input, should it be called MIDIInputEvent? I can imagine future versions of the API wanting to define a MIDIOutputEvent. Otherwise "receivedTime" could be changed back to "timestamp". I'm afraid I missed the debate on that subject. Link?

best,
James

**Comment by notator** [comment]
Having a DOMHRT MIDI Timer is no longer an issue, so I'm closing this thread.
MIDIEvent constructors might be useful when dealing with Standard MIDI Files, so I'll continue this brainstorming on the current "MIDIEvent lacking constructor" thread.
