### ISSUE TITLE
MIDI Real-Time status messages - clarification needed

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-midi-api#47]
Need to detail how MIDI RT messages are dispatched when they occur DURING system exclusive messages.

**Comment by cwilso** [comment]
Fixed by https://github.com/WebAudio/web-midi-api/commit/84a7e3e9e294c04570d06bcd95dc1c9d4289c974.

**Comment by agoode** [comment]
Two things:
1. Real-time messages can occur within ANY message, including the normal non-sysex messages. You might want to clarify this.
2. It would be nice to have a similar policy for send as well. It is not clear if I am allowed to intersperse real-time messages within my other messages. I see that running status is explicitly disallowed. Please give a note either way here.

**Comment by cwilso** [comment]
1. Not according to the MIDI Message table [http://www.midi.org/techspecs/midimessages.php] , they cannot.  (" (Note: Real-Time messages ONLY may be interleaved with a System Exclusive.)")

**Comment by cwilso** [comment]
1. fixed.

**Comment by agoode** [comment]
Thanks for clarifying!

**Comment by agoode** [comment]
As we discussed today, we've read this backwards. Sysex is only allowed to be interrupted by real-time messages, but they can occur in between any 2 bytes.

Is there an update needed here?

**Comment by cwilso** [comment]
Sigh.  Yes.  It's possible to intersperse RT messages inside short messages as well.
