### ISSUE TITLE
"Message" event needs to be renamed to "MIDIMessage".

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-midi-api#50]
There's already a "message" event for receivers of postMessage()-sent data, and this will get confusing.  Rename to "midi"?  "midimessage"?

**Comment by toyoshim** [comment]
Hum... WebSocket also have another "message" event.
"close" is conflicted between WebSocket and Notification, too.

If we should avoid name conflict, I prefer "midimessage" though this is a little long word.

**Comment by cwilso** [comment]
Fixed.

**Comment by jussi-kalliokoski** [comment]
Can a MIDIPort really ever be a receiver of postMessage messages so that these would conflict?

**Comment by marcoscaceres** [comment]
Yeah, I can't really think how to wire that up.
