### ISSUE TITLE
ErrorCallback/SuccessCallback should be named MIDIErrorCallback/MIDISuccessCallback

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#51]
SuccessCallback and ErrorCallback have too generic names.
At least, ErrorCallback is conflicted with FileSystem API.

I suggest these names are changed to MIDISuccessCallback and MIDIErrorCallback.

**Comment by marcoscaceres** [comment]
I disagree. These are just callbacks (i.e., they are just functions). The names don't conflict in practice - they are just spec writing aids.

**Comment by toyoshim** [comment]
Practically, WebKit and Blink(Chromium) need to define unique IDL for these callbacks implementation because it generate C++ bindings as a class respectively. I feel it's better to use the same name between the spec and implementations. What do you think about it? I'm not sure if it's fine that an implementation matter affect the spec.

**Comment by marcoscaceres** [comment]
@toyoshim totally agree. It would be best to use the same name for callbacks if they do exactly the same thing. I think the best course of action to make that happen would be for generic "SuccessCallback" and "ErrorCallback" to just be defined in Web IDL so authors can just reference them. They should be part of the common definitions:

http://dev.w3.org/2006/webapi/WebIDL/#common 

The other option is just to use Function (http://dev.w3.org/2006/webapi/WebIDL/#common-Function).  

BTW, please be aware that there is a discussion of using a Future for this particular aspect of the API.

**Comment by cwilso** [comment]
Fixed.

**Comment by jussi-kalliokoski** [comment]
Aww, man, I was so happy to simplify the names. MIDI{Error,Success}Callback is really ambiguous: "Musical Instrument Digital Interface success callback". That makes no sense, the MIDI there adds no value, unless confusion is a value. ;)
