### ISSUE TITLE
ErrorCallback/SuccessCallback should be named MIDIErrorCallback/MIDISuccessCallback

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-midi-api#53]

**Comment by marcoscaceres** [comment]
... or Function ;)  But I'll defer to actual implementers.

**Comment by toyoshim** [comment]
Yeah, also we already had a issue for this topic https://github.com/WebAudio/web-midi-api/issues/51

**Comment by cwilso** [comment]
Doh.  I don't know how I missed that previous issue.
