### ISSUE TITLE
Doing edits to spec through pull requests

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#55]
Can we change the editorial process a bit so that changes to the spec are done through pull requests? That way, each request gets a review before a merge is made.

I promise to review changes within 12-24 hours (usually less).

**Comment by jussi-kalliokoski** [comment]
Neverrrr, all I type is perfect and needs no review! It'll mess up my flow! My creativity will be stifled and you know...

(That's a yes sirree)

**Comment by cwilso** [comment]
I'm not going to promise to be perfect on this, particularly for typo fixes, but I'll try.  :)
