### ISSUE TITLE
Error types in the spec need to match DOM4

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#57]
The spec currently contains some error names that don't exist in DOM4. Please make sure the spec aligns with the DOM4 error names: 

http://dom.spec.whatwg.org/#error-names-table

Please note also that when you throw an exception, it should be written like this: 

> When x happens, [throw](http://dev.w3.org/2006/webapi/WebIDL/#dfn-throw) a "WhatEver" exception.

I.e., please don't use the old UPPER_CASE style, and just link to "throw" in DOM4.

**Comment by cwilso** [comment]
The only type that doesn't exist in the DOM4 spec is TypeError, which is a type in ECMAScript.  Is that problematic?  It's correctly representative.

**Comment by marcoscaceres** [comment]
TypeError is fine. 

You have some typos is all :smile:. The problems ones are:
- NOT_FOUND_ERROR should be NOT_FOUND_ERR
- NOT_SUPPORTED_ERROR should be NOT_SUPPORTED_ERR

(actually, the above should be changed to their lower case equivalents)

**Comment by cwilso** [comment]
Ah.  Replaced them all with lower case equivalents anyway.  :)

**Comment by marcoscaceres** [comment]
heh, saw that right after I hit the comment button :)
