### ISSUE TITLE
Introduction - editiorial issues

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#60]
The second paragraph starts with:

> This API has been defined with a wide variety of use cases in mind.

But then continues talking about how it is supposed to work on top of windows and core audio. I think that the sentence above should be dropped (as being implementable on-top of windows and core audio are goals, but not use cases).

**Comment by cwilso** [comment]
Moving that sentence, as it wasn't clear from the flow.  The first para describes all the use cases; the second para says "we solve these just like Windows MIDI and CoreMIDI".  That sentence was supposed to be a segue between the two, but clumsily inserted.
