### ISSUE TITLE
obtaining a promise and related terminology 

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#65]
The spec says: 

> "Obtains a Future interface representing a request for access to MIDI devices on the user's system."

Please remove this. It's already in step 1 of the "algorithm to request MIDI Access". 

Also, the spec says:

> Create a Future object that will run the following steps 

It's not the "Future" that runs the steps. It's the user agent. 

Please change the text to:

> 1. Let <var>future</var> be a new Future object and <var>resolver</var> its associated resolver.
> 2. Return <var>future</var>. 
> 3. ...

**Comment by marcoscaceres** [comment]
BTW, please see the following link for how to write an algorithm that users futures:
http://web-alarms.sysapps.org/#taskscheduler-getpendingtasks

We had Anne and Alex check the above and they said it was written correctly. It would be good to model any Promise related text after the above (I think Future's resolver handles a bunch of stuff that doesn't need to be in the MIDI spec).

**Comment by cwilso** [comment]
Thanks for the example.

**Comment by marcoscaceres** [comment]
Please note that `.done()` got nuked also. It's used in an example. Please change it for `.then()` to be safe.

**Comment by cwilso** [comment]
I know.  We had a long internal back and forth on all the changes from the
last TC39 meeting.  :)

**Comment by marcoscaceres** [comment]
heh, good to know someone knows what the hell is going on with all that stuff :)

**Comment by cwilso** [comment]
I did not make THAT claim.  :)  Much like Thomas Edison, I just found one
more way that was wrong.  :)
