### ISSUE TITLE
MIDIOuput.send "timestamp" parameter is not enougth or too much

### ISSUE THREAD

**Issue by nfroidure** [WebAudio/web-midi-api#74]
In order to illustrate the feel i have about the current Web MIDI API implementation, i listed the following use cases that, i mean, the API should be designed for :
1 - sending realtime MIDI events : being able to just play a note now. It is important for playing sounds when events like user interaction, errors etc. occurs. It fit the needs of video games, virtual instruments etc.
2 - playing a MIDI incoming stream (there is a node project to broadcast MIDI with websockets).
3 - playing a MIDI file.
4 - composing a MIDI sequence.

The midiOutput.send method successfully covers the first case ( the timestamp parameter, isn't needed).

The second case is a bit more complex. In fact, with the current API, it would imply to : 
- manage an outputBuffer in order to avoid eventual network problems to impact the note timing.
- manage an event queue in order to avoid MIDI to continue playing if the user want to listen to another MIDI stream.

The third case will also have to manage it's own event queue to allow users to be able to stop the MIDI player. It will also have to resend and resend the same datas to the midiOutput if the user decides to replay a sequence or to move into that sequence. The MIDI player will also have to predict the "end" of the MIDI output because there is no way to know when every events sent to a midiOutput have been played.

The fourth case will also have to manage an event queue and to often resend the same datas to the midiOutput cause many sound editors consist of looping in the same sequence that is modified on the fly.

So, as a conclusion of it, the first thing i mean is what's the timestamp parameter purpose if the users finally have to manage elapsed time ? I think that if we just have the send method to deal with midi output, then, the timestamp param is not usefull at all. It just make a false promise.

Sure, having the API managing time for us in another thread could be a great feature because the setTimeout callback execution time is unpredictable. But, it actually provide it in a manner that will lead to the fact that playing MIDI will always rely on setTimeout to manage event queues, output buffers and end of outputs.

That's why i think that timestamp parameter should be removed. It doesn't mean i do not want the Web MIDI API to manage time for us, i actually think it's better to let native code manage time instead of doing it in the main JS thread with all the possible problems that could appear with concurrent code execution.

But i think that if we let the Web MIDI API manage time, we should let him the keys to do so. That was the purpose of my suggestion of using MIDI Events Sequences with delta times. I think it's the good way to let the Web MIDI API manage time for us, better than us with our setTimeout caveats.

It could just be done with something like this : 

``` js

// MIDI composition
var sequence=new Uint8Array(1000);
midiOutput.setSequence(sequence);
midiOutput.play(Infinity); // looping (play Infinity times)
// modify sequence
midiOutput.pause();
sequence[0]=0x1F; // delta time
sequence[1]=0x90; // noteOn
sequence[2]=0x30; // note C
sequence[0]=0x79; // velocity 121
midiOutput.resume();

// MIDI file play
var sequence; // contains every track sequence
midiOutput.setSequence(sequence);
midiOutput.play(1); // play one time
// navigate througth the sequence
midiOutput.setOffset(0); // restart

// MIDI incoming stream
var buffer=new Uint8rray(1000);
midiOutput.setSequence(buffer);
// waiting for the buffer to be full
var newBuffer=new Uint8rray(1000);
midiOutput.play();
// second buffer full
midiOutput.appendSequence(newBuffer);
```

So each need would be fit, with great time precision, ease of use and a promise really fullfulled. Another advantage of MIDI Event sequences is that it's a strong standard that is designed to be lightweight, after all it's just MIDI !

PS: That's my last issue ;)

Note: This issue, is a reformulation of the following messy issues: 
https://github.com/WebAudio/web-midi-api/issues/73
https://github.com/WebAudio/web-midi-api/issues/72

**Comment by cwilso** [comment]
The premise of the Web MIDI API is to expose the underlying capabilities in a way that can be used to produce high-quality timing for MIDI applications.  Managing entire queues quickly becomes a Media Player-like venture - which can, frankly, already be handled by Media Player or the like.  At the same time, the ability (via optional timestamps) needs to be given to schedule sends at precision greater than that accesible through setTimeout.

This approach directly mirrors what Web Audio does - it has a clock, and timestamps, but you will still have to manage the "queue" yourself (if you're implementing a drum machine, e.g.).  I went into great detail on the reasons for this design in an HTML5Rocks article: http://www.html5rocks.com/en/tutorials/audio/scheduling/.

It's quite easy to recast your code in current terms, minus the "pause()" - and that pause(), and the associated editing-while-playing, causes all kinds of race conditions (lots of issues around whether sequence[] can be modified after being setSequence()d, etc.).  The current design is simple, provides the needed tools, and mirrors the existing patterns for MIDI access.  A change of the type you suggest also makes it much more complex to send messages immediately, and to a value that I don't think as many people would need as you suggest.
