### ISSUE TITLE
Cancel/stop a scheduled message?

### ISSUE THREAD

**Issue by tomconnors** [WebAudio/web-midi-api#76]
Hi there,
I wasn't able to find in the spec any means by which to cancel a scheduled message. Suppose, for instance, I want to schedule an entire midi track to play, but allow stopping playback before the end of the track. Should a predefined method of cancelling a message exist, or should I just send a note off event for the same note/time?

btw, thanks a bunch for the work on this. I'm really excited about this api.

**Comment by nfroidure** [comment]
By reading this thread, you'll see that the current version of the spec is not intended to send a complete midi track to the output : https://github.com/WebAudio/web-midi-api/issues/74

In fact, you'll have to send midi events progressively to the output and maintain an array with current "on" note for each instruments to be able to set them "off" in case the play is paused.

**Comment by tomconnors** [comment]
Ah makes sense. Thanks for the info.

**Comment by dhnhgd** [comment]
> Hi there, I wasn't able to find in the spec any means by which to cancel a scheduled message. Suppose, for instance, I want to schedule an entire midi track to play, but allow stopping playback before the end of the track. Should a predefined method of cancelling a message exist, or should I just send a note off event for the same note/time?
> 
> btw, thanks a bunch for the work on this. I'm really excited about this api.

https://github.com/WebAudio/web-midi-api/issues/76#issue-17264627
