### ISSUE TITLE
DOMError for the system returning an error to initialize MIDI system on requestMIDIAccess

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#77]
In the spec, 4.1.1 Methods; requestMIDIAccess, step 9,

it said that DOMError can be "SecurityError" or "NotSupportedError". But I think both are not reasonable when the OS or some underlying systems return an error to initialize MIDI systems.

I chatted with other engineers working on filesystem API, and now I feel "InvalidStateError" sounds reasonable and consistent with other APIs.

WDYT?

**Comment by toyoshim** [comment]
FYI, Chrome tentatively implements this error.
https://code.google.com/p/chromium/issues/detail?id=260315

**Comment by jussi-kalliokoski** [comment]
`"InvalidStateError"` SGTM

**Comment by marcoscaceres** [comment]
FWIW, WFM also.
