### ISSUE TITLE
Tweaks requested for publishing

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-midi-api#94]
From Doug while publishing last public draft:

The updated Working Draft of the Web MIDI API spec was published today [1], as planned.

I took the liberty of adding a few more headers:
- the WG name
- comments link (to the mailing list)
- link to the test suite (currently Jussi's github repo, but I'd like an official URL next time)

If you don't want these, we can take them out next time, but I think people find them more useful at the top than hidden in the "status" section.

There were 3 validation errors (all duplicate IDs between "MIDIInputMap" and "MIDIOutputMap" interface descriptions), and several broken links or broken fragment ids (notably, a couple internal broken ids, a broken link to Jussi's old website which I updated, and broken links to the HTML5 editor's draft which I changed to the TR version). Jussi, Chris, please change these in the Editor's Draft for next time.

[1] http://www.w3.org/TR/2013/WD-webmidi-20131126

**Comment by marcoscaceres** [comment]
Thanks for adding the additional links at the top! These are really helpful.

**Comment by cwilso** [comment]
I believe these have all been addressed in the ED.
