### ISSUE TITLE
`inputs` and `outputs` are functions?

### ISSUE THREAD

**Issue by drewish** [WebAudio/web-midi-api#96]
The spec and chrome's implementation seem to diverge a little on the `midiAccess.inputs` and `outputs`. The implementation has those as functions:

```
> midi.inputs
function inputs() { [native code] }
> midi.inputs()
[ MIDIInput ]
```

So it seems that the examples like:

``` js
function listInputsAndOutputs( midiAccess ) {
  for (var input in midiAccess.inputs()) {
    console.log( "Input port [type:'" + input.type + "'] id:'" + input.id +
      "' manufacturer:'" + input.manufacturer + "' name:'" + input.name +
      "' version:'" + input.version + "'" );
  }
}
```

Should be invoking the function:

```
>  for (var input in midiAccess.inputs) {
    console.log( "Input port [type:'" + input.type + "'] id:'" + input.id +
      "' manufacturer:'" + input.manufacturer + "' name:'" + input.name +
      "' version:'" + input.version + "'" );
  }
undefined
>  for (var input in midiAccess.inputs()) {
    console.log( "Input port [type:'" + input.type + "'] id:'" + input.id +
      "' manufacturer:'" + input.manufacturer + "' name:'" + input.name +
      "' version:'" + input.version + "'" );
  }
Input port [type:'undefined'] id:'undefined' manufacturer:'undefined' name:'undefined' version:'undefined' VM151:3
undefined
```

I'm happy to create a PR that updates these but I wanted to be sure that Chrome's code (34.0.1781.0 canary) is correct and not the other way around.

**Comment by cwilso** [comment]
Chrome's implementation hasn't caught up to the spec yet, so no, don't
create a PR for the Web MIDI spec.

**Comment by drewish** [comment]
Great, closing this then.

**Comment by drewish** [comment]
Humm, I was hoping the WebMIDIAPIShim would match the spec but it seems to be implementing those as functions as well.

**Comment by cwilso** [comment]
I probably won't update the shim until Chrome updates, at least not the main branch.
